Buffet/ViewModels/Shared/TabelaDeStatusPartialViewModel.cs
using System;
using System.Collections.Generic;

namespace Buffet.ViewModels.Shared
{
    public class Status
    {
        public int Id { get; set; }
        public String Descricao { get; set; }
    }

}

Buffet/Controllers/AcessoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Buffet.Models.Acesso;
using Buffet.Models.Buffet.Cliente;
using Buffet.RequestModels;
using Buffet.ViewModels.Acesso;
using Microsoft.AspNetCore.Mvc;

namespace Buffet.Controllers
{
    public class AcessoController : Controller
    {
        private readonly AcessoService _acessoService;

        public AcessoController(AcessoService acessoService)
        {
            _acessoService = acessoService;
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult RecuperarConta()
        {
            return View();
        }

        //o browser faz requisições via get quando clicamos em um link, como por exemplo a cadastrar 
        //ma tela de login, por isso ele entra aqui inicialmente
        [HttpGet]
        public IActionResult Cadastrar()
        {
            var viewmdel = new CadastrarViewModel();

            viewmdel.Mensagem = (string) TempData["msg-cadastro"];
            viewmdel.ErrosCadastro = (string[])TempData["erros-cadastro"];    
            
            return View(viewmdel);
        }
        
        //Ideia: clica no formulario, ele e post, vc processa os dados e em seguida ele devolver o retorno
        //para o HTTPget
        [HttpPost]
        public async Task<RedirectToActionResult> Cadastrar(AcessoCadastrarRequestModel request)
        {
            var email = request.Email;
            var senha = request.Senha;
            var senhaConfimacao = request.SenhaConfirmacao;

            if (email == null){
                TempData["msg-cadastro"] = "Por favor informe o e-mail";

                return RedirectToAction("Cadastrar");
            }

            try
            {
                await _acessoService.RegistrarUsuario(email, senha);
                TempData["msg-cadastro"] = "Cadastro realizado com sucesso, faça o login";
                return RedirectToAction("Login");
            }
            catch (CadastrarUsuarioException exception)
            {
                var listaErros = new List<string>();
                
                foreach (var identityError in exception.Erros)
                {
                    listaErros.Add(identityError.Description);
                }
                
                TempData["erros-cadastro"] = listaErros;

                return RedirectToAction("Cadastrar");
            }
            
        }
    }
}       

Buffet/Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Buffet.Controllers.Admin
{
    //bloqueio de controller para usuarios não autorizados, metodo natural do asp.net
    //so podem acessar usuarios com a devida autorização
    [Authorize]
    public class AdminController : Controller
    {
        public AdminController()
        {
        }

        
        public IActionResult Supervisao()
        {
            return View();
        }
    }
}

Buffet/Controllers/AjudaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace Buffet.Controllers
{
    public class AjudaController : Controller
    {
        public AjudaController(){
        }

        public IActionResult Index()
        {   
            return View();
        }
    }
}

Buffet/Controllers/InformacoesLegaisController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace Buffet.Controllers
{
    public class InformacoesLegaisController : Controller
    {
        public InformacoesLegaisController(){
        }

        public IActionResult TermosDeUso()
        {   
            return View();
        }
        
        public IActionResult PoliticaDePrivacidade()
        {   
            return View();
        }
    }
}

Buffet/Views/Shared/_LayoutExterno.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/layout-externo.css"/>
    @RenderSection("Styles", required:false)
</head>
<body>

<nav class="navbar sticky-top flex-md-nowrap p-0">
    <div>
        <a href="/">Buffet Magister</a> 
    </div>
    <div class="text-right small">
        <a asp-controller="InformacoesLegais" asp-action="TermosDeUso">Termos de Uso</a>
        -
        <a asp-controller="InformacoesLegais" asp-action="PoliticaDePrivacidade">Políticas de Privacidade</a>
    </div>
</nav>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Buffet Magister
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/layout-externo.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Buffet/Views/Shared/_LayoutInterno.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/layout-interno.css"/>
    @RenderSection("Styles", required: false)
</head>
<body>

<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/">Buffet Magister</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" asp-controller="Acesso" asp-action="Login">Sair</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky pt-3">
                
                <div class="text-center mb-5">
                    Leonardo
                    <br>
                    <a asp-controller="PainelDoUsuario" asp-action="Index">Painel</a>
                </div>

                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Admin" asp-action="Supervisao">
                            <span data-feather="home"></span>
                            Supervisao
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Seção 01
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Seção 02
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Seção 03
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Seção 04
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Seção 05
                        </a>
                    </li>
                </ul>

                <div class="text-center small mt-5">
                    <a asp-controller="Ajuda" asp-action="Index">Ajuda</a>
                    <br>
                    <a asp-controller="InformacoesLegais" asp-action="TermosDeUso">Termos de Uso</a>
                    <br>
                    <a asp-controller="InformacoesLegais" asp-action="PoliticaDePrivacidade">Políticas de Privacidade</a>
                </div>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">@ViewData["Title"]</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    @RenderSection("Toolbar", required:false)
                </div>      
            </div>
            
            @RenderBody()
        </main>
    </div>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/layout-externo.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>